### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by amstocker** [ipfs/py-ipfs-api#26]
Here are some things I'd like to work on over the next couple weeks:

- documentation
    - [ ] write doc strings for all api methods
    - [ ] make a readthedocs.org page
- file streaming
    - [x] chunk large files and multiple files instead of adding them all to the same buffer
    - [x] use file streaming for all add operations, not just recursive add
    - [x] support `ipfs get`, i.e. streaming files/directories directly to disk (re: #28)
- async
    - [ ] edit: make client more friendly for async integration

**Comment by BrendanBenshoof** [comment]
I'm concerned with trying to integrate any of the async libraries.
The current state of Async in python is kinda fractured and I think the best thing we can do is make it as easy as possible to integrate into any such solution as possible.

Could you expand on "tools for mapping data to commands"?

**Comment by amstocker** [comment]
Yeah thats true, for 2.x there is gevent and tornado, then builtin async in 3.x, etc.  You're right we should just make it easy to implement.  By mapping data to commands I meant something like:

```python

def map(command, requests):
    jobs = []
    for r in requests:
        args = r
        jobs.append( async_spawn(command, args) )
    joinall(jobs)
    return [job.result for job in jobs]

results = map(api.name_resolve, [
    "/ipns/<mhash1>",
    "/ipns/<mhash2>",
    "/ipns/<mhash3>"
])

```

**Comment by moreati** [comment]
I'm working on the doc strings, pull request in the next few days

**Comment by amstocker** [comment]
@moreati awesome!  looking forward to it

**Comment by whereswaldon** [comment]
Is anyone still working on parts of this checklist? If not, I think we should close the issue.

**Comment by alexander255** [comment]
We probably should create new issues for the remaining tasks (docs, doc hosting, async), then close this.

**Comment by whereswaldon** [comment]
Sounds good. I'll do that now.
